import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'hermango',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  auth,
}: {
  children: React.ReactNode,
  auth: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
