name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          host: ${{ secrets.ALI_SERVER_HOST }}
          user: ${{ secrets.ALI_SERVER_USER }}
          pass: ${{ secrets.ALI_SERVER_PASS }}
          connect_timeout: 60s
          scp: |
            ./* => /www/hermango
          last_ssh: |
            cd /www/hermango
