name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.ALI_SERVER_HOST }}
          user: ${{ secrets.ALI_SERVER_USER }}
          pass: ${{ secrets.ALI_SERVER_PASS }}
          connect_timeout: 60s
          scp: |
            ./* => /www/hermango
          last_ssh: |
            cd /www/hermango
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            pnpm run deploy
